output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# SEE: https://golangci-lint.run/usage/configuration/
linters-settings:
  godox:
    keywords:
      - "BUG"
      - "FIXME"
    #  - "TODO"
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: snake
  varnamelen:
    max-distance: 5
    min-name-length: 3
    check-receiver: false
    check-return: false
    check-type-param: false
    ignore-type-assert-ok: false
    ignore-map-index-ok: false
    ignore-chan-recv-ok: false
    ignore-names:
      - err
      - to
      - db
      - id
    ignore-decls:
      - t testing.T
      - f *foo.Bar
      - e error
      - i int
      - const C
      - T any
      - m map[string]int
      - to time.Time
      - x int
      - y int
      - w io.Writer
      - i int64
      - f *os.File
      - d Discordant

linters:
  enable-all: true
  disable:
    - exportloopref # is deprecated (since v1.60.2)
    - exhaustruct # mad linter
    - tagalign # I don't think that tags align is a good idea
    - wrapcheck # mad linter
    - mirror
    - ireturn
    - interfacebloat

issues:
  exclude:
  exclude-rules:
  exclude-dirs:
    - vendor/
  exclude-files:
    - ".*_test.go$"
